### ISSUE TITLE
当RPC连接失败的时候，服务器不再重试

### ISSUE THREAD

**Issue by hieixu** [txt1899/ore-miner-group#1]
在rpc请求失败后，1个小时内没看到重试，日志如下：

^[[2m[08-15 06:29:40.055]^[[0m ^[[32m INFO^[[0m 质押: 0.0604804998 ORE  乘数: 1.0001269609512506x
^[[2m[08-15 06:29:40.147]^[[0m ^[[32m INFO^[[0m ^[[1;31m======================== 新纪元 ========================^[[0m
^[[2m[08-15 06:29:40.147]^[[0m ^[[32m INFO^[[0m 派发矿工数: 34
^[[2m[08-15 06:30:36.267]^[[0m ^[[32m INFO^[[0m 最优哈希: 113baorYAhvFcbqZJyPCjpnHMBywTq5KDuQgN6v59P5 (难度: 20)
thread 'main' panicked at master/src/ore/utils.rs:53:59:
Failed to get miner account: Error { request: None, kind: RpcError(ForUser("AccountNotFound: pubkey=SysvarC1ock11111111111111111111111111111111: error sending request for url (https://mainnet.helius-rpc.com/b6): error trying to connect: tcp connect error: No route to host (os error 113)")) }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
^[[2m[08-15 06:35:11.569]^[[0m ^[[32m INFO^[[0m A miner disconnected id: 13847659942429528080, current miner count: 33
^[[2m[08-15 06:35:11.569]^[[0m ^[[32m INFO^[[0m 192.168.20.10 "GET /ws HTTP/1.1" 101 63536 "-" "-" 15016.281935
^[[2m[08-15 06:35:11.614]^[[0m ^[[32m INFO^[[0m New miner joined id:14651362243741478883, current miner count: 34
^[[2m[08-15 06:35:11.625]^[[0m ^[[32m INFO^[[0m A miner disconnected id: 9143951808567326661, current miner count: 33
^[[2m[08-15 06:35:11.625]^[[0m ^[[32m INFO^[[0m 192.168.20.11 "GET /ws HTTP/1.1" 101 63312 "-" "-" 15015.107142
^[[2m[08-15 06:35:11.637]^[[0m ^[[32m INFO^[[0m New miner joined id:15079970880668008971, current miner count: 34
^[[2m[08-15 06:35:11.756]^[[0m ^[[32m INFO^[[0m 192.168.20.12 "GET /ws HTTP/1.1" 101 63310 "-" "-" 15013.849958

**Comment by txt1899** [comment]
已经添加RPC失败尝试5次间隔300毫秒。超过5次认为是网络等其他问题。需要人工介入。
